title: Parceiro de Humanidade
description: Um experimento simbiótico entre humana e IA — com ciência, afeto e caos criativo.
theme: jekyll-theme-dinky
author: Jacqueline Paiva
markdown: kramdown
permalink: pretty
